### ISSUE TITLE
Funflow-CWL Project Features

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/funflow#100]
These are a few features that would be nice additions to the funflow-cwl project:

- Providing an option to copy the files produced in the store (as output from the CWL tool or workflow) into the directory in which `ffcwlrunner` is called

- Allowing CWL files to have default values; this is quite tricky and amounts to treating the input of type `t` as type `Maybe t` and preprocesing the job file to reflect this

- Supporting CWL records. Hopefully by using my 'generic-data' library.

- CWL pre-processing rules (as per the SALAD specification)

- CWL Expression Tools

**Comment by mboes** [comment]
Could you split those out into separate tickets with a label, say "CWL" label?

**Comment by Divesh-Otwani** [comment]
Done.
