### ISSUE TITLE
CWL: Allow default values

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/funflow#102]
Allow CWL files to have default values; this is quite tricky and amounts to treating the input of type t as type Maybe t and preprocesing the job file to reflect this. Also, this change would need to be propagated along all intermediate CWL files (and it might even involve back tracking).

**Comment by cfhammill** [comment]
Maybe consider writing a dhall wrapper around CWL? https://github.com/dhall-lang/dhall-lang

**Comment by dorranh** [comment]
Closing this issue since `funflow-cwl` is not included in funflow v2.x. If there is interest in porting CWL support then I would ask users to please create a new feature request expressing interest.
