### ISSUE TITLE
CWL: Follow the preprocessing rules

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/funflow#104]
Follow the [salad](https://www.commonwl.org/v1.0/SchemaSalad.html) specification to pre-process the input CWL and job files.

**Comment by curiousleo** [comment]
Related: https://github.com/tweag/funflow/issues/149

**Comment by dorranh** [comment]
Closing this issue since `funflow-cwl` is not included in funflow v2.x. If there is interest in porting CWL support then I would ask users to please create a new feature request expressing interest.
