### ISSUE TITLE
Displaying stderr emitted by external processes

### ISSUE THREAD

**Issue by mpickering** [tweag/funflow#106]
I have created a `SimpleFlow` using `external`. The process takes quite a long time to run and I would like to keep updated with the progress. Any output on stderr or stdout is captured and not displayed until the process has completed. Is there any way display log messages incrementally?

**Comment by hughjfchen** [comment]
Is this problem solved for the newest release?

**Comment by vreuter** [comment]
This was closed by merge of https://github.com/tweag/funflow/pull/177, which included a commit with keyword text aimed at an issue in the `funflow2` repo.

**Comment by dorranh** [comment]
Thanks @vreuter! GitHub is quite aggressive with linking commits with issues. 

We recently integrated the contents of funflow v2 with the main funflow repository. The newer version actually no longer uses the same approach to executing external tasks. As of writing this, external tasks can be executed in a Docker sandbox via a [DockerTask](https://tweag.github.io/funflow/api/funflow/html/Funflow-Tasks-Docker.html) which reports the container's stdout/stderr in real-time as requested in this issue.
