### ISSUE TITLE
Using mergeDirs can defeat caching

### ISSUE THREAD

**Issue by mpickering** [tweag/funflow#110]
The final thing that I had to suss out was that `mergeDirs` does create a new entry in the store. 

This was breaking recompilation for me as I had a step which looked like.

```
keys <- mergeDirs <<< mapA foo -< inp
res <- processKeys -< keys
```

1. Content store paths ended up in the files outputted by `processKeys`.
2. `processKeys` grouped together different files which were the result of `foo` so sometimes the group contained one file but had a different hash because of more inputs being passed to `mergeDirs`. 

The way that I fixed this was to make `processKeys` take a list of paths rather than a directory and pass directly the result of `mapA foo`.

This ticket can probably just be closed but writing this information down might save someone else some time.

**Comment by dorranh** [comment]
Closing this issue since `mergeDirs` is no longer used in funflow2.
