### ISSUE TITLE
Control.Funflow.Exec.Simple should export precanned SQLite and Redis functions

### ISSUE THREAD

**Issue by mpickering** [tweag/funflow#115]
There is quite a chasm between the simplicity of `withSimpleLocalRunner` and `runSimpleFlow`. It would be useful to add similar functions which "just work" for sqlite and redis as well.

For example, this function would be useful to provide.

https://github.com/tweag/funflow/blob/0446fa673a02a1aa286c2f885c0709acf8790655/funflow/test/Funflow/SQLiteCoordinator.hs#L64

**Comment by dorranh** [comment]
Closing this issue since we are no longer using `external-executor`.
