### ISSUE TITLE
Should it be possible to combine two Env values?

### ISSUE THREAD

**Issue by mpickering** [tweag/funflow#126]
Given two `Env` values, their composition is not always well-defined. 

In particular, there's no way to combine together an `ImplicitEnv` and an `ExplicitEnv`. It would be
useful for this composition to produce a `SemiImplicitEnv` which inherits the environment but also sets some variables. 

Perhaps a suitable monoid would look like:

```
m <> ImplicitEnv = ImplicitEnv 
ImplicitEnv <> ExplicitEnv e = SemiImplicitEnv e
ImplicitEnv <> e = e
SemiImplicitEnv e1 <> SemiImplicitEnv e2 = SemiImplicitEnv (e1 <> e2)
SemiImplicitEnv e1 <> ExplicitEnv e  = SemiImplicitEnv (e1 <> e)
```

**Comment by dorranh** [comment]
I'm going to go ahead and close this issue since we are not longer using the `ImplicitEnv` / `ExplicitEnv` mechanism.
