### ISSUE TITLE
funflow-cwl README.me unclear

### ISSUE THREAD

**Issue by jrandall** [tweag/funflow#136]
On line 96 of the README.md for funflow-cwl, it says:

```
- We don't support any All outputs must be obtained through globing.
```

This seems to be missing something that explains what it is that is not supported. I am guessing it may have intended to say that it doesn't support any expressions?

**Comment by dorranh** [comment]
Thanks for raising this issue. `CWL` support has since been dropped from `funflow`, so I'm going to go ahead and close this issue.
