### ISSUE TITLE
Build fails with Katip 8.X.X

### ISSUE THREAD

**Issue by rybern** [tweag/funflow#141]
Trying to build funflow (tried 1.4.0, 1.3.2, 1.1.0) with Katip version 8 (tried 8.2.0, 8.1.0, 8.0.0), I get the error:

```
    /run/user/1000/stack-0f94e8531f695034/funflow-1.4.0/src/Control/Funflow/External/Executor.hs:165:43: error:
        * Couldn't match expected type `Item a -> IO Bool'
                      with actual type `Severity'
        * In the third argument of `mkHandleScribe', namely `InfoS'
          In the second argument of `(=<<)', namely
            `mkHandleScribe ColorIfTerminal stdout InfoS V2'
          In the expression:
            executeLoopWithScribe coord cfg store
              =<< mkHandleScribe ColorIfTerminal stdout InfoS V2
        |
    165 |     mkHandleScribe ColorIfTerminal stdout InfoS V2
        |                                           ^^^^^
```

Here's the offending line: https://github.com/tweag/funflow/blob/c24cda04296cc0cbab69c1eb9cb8c983ddc65dff/funflow/src/Control/Funflow/External/Executor.hs#L165

This is happening because the signature of mkHandleScribe changed from Katip 7:
http://hackage.haskell.org/package/katip-0.7.0.0/docs/Katip.html#v:mkHandleScribe
to Katip 8:
http://hackage.haskell.org/package/katip-0.8.0.0/docs/Katip.html#v:mkHandleScribe

I suggest either fixing or adding < 8.0.0 to the cabal:
https://github.com/tweag/funflow/blob/c24cda04296cc0cbab69c1eb9cb8c983ddc65dff/funflow/funflow.cabal#L71

**Comment by YPares** [comment]
I think this can be closed know, given we updated the LTS?

**Comment by dorranh** [comment]
There have been a number of changes to funflow since this issue was created. The project does not actually depend on `katip` anymore, so I'm going to go ahead and close this issue.
