### ISSUE TITLE
Relative paths in workflow files not resolved relative to base file

### ISSUE THREAD

**Issue by curiousleo** [tweag/funflow#149]
According to https://www.commonwl.org/v1.1/Workflow.html#WorkflowStep, the `run` field of a WorkflowStep can be of type `string`, amongst others. The specification is not 100% clear on how this should be resolved if it is a relative path. According to https://github.com/common-workflow-language/common-workflow-language/issues/760#issuecomment-416019941 which references https://www.commonwl.org/v1.0/SchemaSalad.html#Link_resolution, the right thing to do is to resolve it relative to the location of the base document.

There is an example of this in this repo: https://github.com/tweag/funflow/blob/ef81892478aff8133c3dcf07149f78be8d3e7c49/funflow-cwl/test/guide/1st-workflow.cwl#L15

It appears that `ffcwlrunner` resolves this relative path against the current working directory instead of against the location of the base document.

This invocation fails when the current working directory is not the same as the base document location:

```
funflow$ stack run ffcwlrunner -- \
    funflow-cwl/test/guide/1st-workflow.cwl \
    funflow-cwl/test/guide/1st-workflow-job.yml \
    store memory
Execution failed: 

YAML exception:
Yaml file not found: tar-param.cwl
```

But it succeeds when they match:

```
funflow/funflow-cwl/test/guide$ stack run ffcwlrunner -- \
    1st-workflow.cwl \
    1st-workflow-job.yml \
    store memory
[2019-10-15 13:21:59][FFExecutorD.executeLoop][Info][think5][PID 6259][ThreadId 4][funflow-1.5.0-5ZjWPNzmXNz2HYO9kPFplI:Control.Funflow.External.Executor src/Control/Funflow/External/Executor.hs:183:9] Initialising connection to coordinator.
[...]
```

My understanding is that the first invocation should be successful too.

**Comment by curiousleo** [comment]
With
```
build:
  library-profiling: true
  executable-profiling: true
```

I get this stack trace:
```
$ stack run --rts-options='-xc' ffcwlrunner -- guide/1st-workflow.cwl guide/1st-workflow-job.yml teststore memory                                                     [27/1962]
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
  Text.Libyaml.decodeFileMarked.alloc,
  called from Text.Libyaml.decodeFileMarked,                                                                    
  called from Text.Libyaml.decodeFile,
  called from Control.Monad.Trans.Resource.Internal.>>=.\,
  called from Control.Monad.Trans.Resource.Internal.>>=, 
  called from Data.Conduit.Internal.Pipe.runPipe,
  called from Control.Monad.Trans.Resource.runResourceT.\.\,
  called from Control.Monad.Trans.Resource.runResourceT.\,
  called from Control.Monad.IO.Unlift.withRunInIO,
  called from Control.Monad.Trans.Resource.runResourceT, 
  called from Data.Yaml.Internal.decodeHelper_,
  called from Data.Yaml.decodeFileWithWarnings,
  called from Data.Yaml.decodeFileEither,
  called from Control.Funflow.CWL.Parse.parseCWLFile.decodeCWLFile,
  called from Control.Funflow.CWL.Parse.parseCWLFile,                                                           
  called from Control.Funflow.CWL.Convert.Workflow.convertNode,
  called from Control.Funflow.CWL.Convert.Workflow.convertToFlows,
  called from Control.Funflow.CWL.Convert.Workflow.convertWorkflow,
  called from Control.Funflow.CWL.Convert.Workflow.convertCWLFile,
  called from Control.Funflow.CWL.Run.tryCompile,
  called from Control.Funflow.CWL.Run.tryRun,
  called from Main.main.run,
  called from Main.main.ioRun,
  called from Main.main
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace:                                                                                                                                                             
  Control.Monad.Trans.Resource.runResourceT.\.\.\,
  called from Text.Libyaml.decodeFileMarked.alloc,  
  called from Text.Libyaml.decodeFileMarked,
  called from Text.Libyaml.decodeFile,
  called from Control.Monad.Trans.Resource.Internal.>>=.\,
  called from Control.Monad.Trans.Resource.Internal.>>=, 
  called from Data.Conduit.Internal.Pipe.runPipe,
  called from Control.Monad.Trans.Resource.runResourceT.\.\,
  called from Control.Monad.Trans.Resource.runResourceT.\,
  called from Control.Monad.IO.Unlift.withRunInIO,
  called from Control.Monad.Trans.Resource.runResourceT, 
  called from Data.Yaml.Internal.decodeHelper_,
  called from Data.Yaml.decodeFileWithWarnings,
  called from Data.Yaml.decodeFileEither,
  called from Control.Funflow.CWL.Parse.parseCWLFile.decodeCWLFile,
  called from Control.Funflow.CWL.Parse.parseCWLFile,
  called from Control.Funflow.CWL.Convert.Workflow.convertNode,
  called from Control.Funflow.CWL.Convert.Workflow.convertToFlows,
  called from Control.Funflow.CWL.Convert.Workflow.convertWorkflow,
  called from Control.Funflow.CWL.Convert.Workflow.convertCWLFile,
  called from Control.Funflow.CWL.Run.tryCompile,
  called from Control.Funflow.CWL.Run.tryRun,
  called from Main.main.run,
  called from Main.main.ioRun,
  called from Main.main
Execution failed: 

YAML exception:
Yaml file not found: tar-param.cwl
```

**Comment by curiousleo** [comment]
The problem is that https://github.com/tweag/funflow/blob/d1d5b8f4cae370fe178d82cf0ec45005604d5a78/funflow-cwl/src/Control/Funflow/CWL/Parse.hs#L505 reads the name of the `run` file directly, which is put without further processing into `WflowStep`:
https://github.com/tweag/funflow/blob/d1d5b8f4cae370fe178d82cf0ec45005604d5a78/funflow-cwl/src/Control/Funflow/CWL/Parse.hs#L514

This filename is then directly passed back into `parseCWLFile`:
https://github.com/tweag/funflow/blob/d1d5b8f4cae370fe178d82cf0ec45005604d5a78/funflow-cwl/src/Control/Funflow/CWL/Convert/Workflow.hs#L178-L179

That is, no explicit resolution against the location of the base workflow file is ever attempted.

**Comment by curiousleo** [comment]
**Checkpoint**

It actually looks like what I was originally investigating is just one specific instance of a class of things not supported by `funflow` at the moment (it is possible that this is already documented somewhere):

- According to [the Workflow spec](https://www.commonwl.org/v1.1/Workflow.html#WorkflowStep), the type of the WorkflowStep `run` field is `string | CommandLineTool | ExpressionTool | Workflow`, but `funflow` assumes it is always a `string`, i.e. a filename; the other types are not supported.
- According to [the SchemaSalad spec](https://www.commonwl.org/v1.0/SchemaSalad.html), a whole bunch of preprocessing mostly to do with resolving URIs relative to base URIs and namespaces should happen. As far as I can tell, this is meant to happen in `PreProcess.hs` but isn't implemented yet.

**Comment by curiousleo** [comment]
(For future reference: I believe that the CWL reference implementation does the resolving somewhere around here: https://github.com/common-workflow-language/cwltool/blob/master/cwltool/load_tool.py#L111)

**Comment by dorranh** [comment]
Closing this since CWL support has since been dropped.
