### ISSUE TITLE
CI doesn't seem to test anything

### ISSUE THREAD

**Issue by YPares** [tweag/funflow#164]
@curiousleo I think the ci.yaml using instanciate doesn't run the tests at all, it might even be possible it doesn't build stuff. I'm asking for your input as you were the last one to modify the ci config. Does `nix-instanciate` build anything?

**Comment by YPares** [comment]
I confirm that currently on master, on my laptop the tests fail.

**Comment by curiousleo** [comment]
From `man nix-build`:
> nix-build is essentially a wrapper around nix-instantiate (to translate a high-level Nix expression to a
> low-level store derivation) and nix-store --realise (to build the store derivation).

https://github.com/tweag/funflow/pull/150/files just replaced `nix-build` with `nix-instantiate`. There was no functional change, it just seemed to work better with `cachix`. Feel free to revert https://github.com/tweag/funflow/pull/150.

**Comment by curiousleo** [comment]
Re-reading the manual, you may be right! `--realise` may be missing.

**Comment by YPares** [comment]
@curiousleo --realise seems to be an arg of `nix-store`, not `instantiate`, but yes it seems to do the job
