### ISSUE TITLE
Lots of issues not updated for a long time

### ISSUE THREAD

**Issue by hughjfchen** [tweag/funflow#168]
There're lots of issues left open for a long time without any update about the status. I'd really like to know the latest status for those issues. Could you update them accordingly?

**Comment by dorranh** [comment]
Hi @hughjfchen, thanks for raising this issue. Last year we reworked lots of the internals of `funflow`, but for the time being development is mostly paused (though issues and external contributions are welcome). We are updating the issues on the repo with up to date information, so I'm going to go ahead and close this issue.
