### ISSUE TITLE
dead link in first notebook

### ISSUE THREAD

**Issue by silky** [tweag/funflow#204]
**Describe the bug**

The link to the "WordCount" tutorial, from the first tutorial ( https://github.com/tweag/funflow/blob/master/funflow-tutorial/notebooks/Tutorial1.ipynb ) is dead - https://github.com/tweag/funflow/blob/2c7c568fb1126a631487cee83ea99808ed6c0fc2/funflow-tutorial/notebooks/WordCount.html

**Comment by dorranh** [comment]
I suspect this is related to #203 since they are all hosted on the same site.

**Comment by dorranh** [comment]
Fixed in #205
