### ISSUE TITLE
Run non-determistic tasks

### ISSUE THREAD

**Issue by regnat** [tweag/funflow#76]
It can be useful to run some non-deterministic external tasks as part of a flow (which concretely means having a task which will be re-performed every time regardless of its inputs).

Before #75, this could be easily simulated by adding a random noise to the input of the task to force its input hash to change, but since this isn't possible anymore (and I assume #75 has good reasons not to be reverted), it would be nice to have this built into funflow directly (for example by adding a `_deterministic` field to `Control.Funflow.External.ExternalTask`, but there might be better ways to do this)

**Comment by nc6** [comment]
Ah, indeed, that's a use we hadn't considered when merging that PR. I'll try to address this today.

**Comment by CMCDragonkai** [comment]
I have a task that is meant to randomise the inputs and produce random outputs. Is this relevant? (It's for randomising the sample space of a dataset).

**Comment by nc6** [comment]
@CMCDragonkai Assuming this task takes the same input and you want it to produce different output, then yes. Though in that case I might suggest that you actually thread the seed into the computation, which would have the same result but would mean you could control this later.

**Comment by regnat** [comment]
Fixed by #79
