### ISSUE TITLE
Funflow 1.0.0 is not buildable with hinotify 0.3.10

### ISSUE THREAD

**Issue by Shimuuar** [tweag/funflow#83]
Type signature in 3.10.0 changed from  
`addWatch :: INotify -> [EventVariety] -> FilePath -> (Event -> IO ()) -> IO WatchDescriptor` to `addWatch :: INotify -> [EventVariety] -> RawFilePath -> (Event -> IO ()) -> IO WatchDescriptor`. 

Please change constraint to `==0.3.9` on hackage

**Comment by nc6** [comment]
This should now have been addressed.
