### ISSUE TITLE
Versions of Funflow on Hackage cannot be built when included in cabal

### ISSUE THREAD

**Issue by KirinDave** [tweag/funflow#97]
Currently every version of Funflow on Hackage cannot be built as a dependency. Version 1.0.0 fails due to https://github.com/tweag/funflow/issues/83, and subsequent versions appear to have incoherent dependencies around `async 2.1.1.1` and `hinotify`.

Example failure: 

```
$ cabal new-build
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: funflow-1.3.1 (dependency of ff-client-0.1.0.0)
next goal: hinotify (dependency of funflow-1.3.1)
rejecting: hinotify-0.4 (conflict: funflow => hinotify==0.3.9)
trying: hinotify-0.3.9
trying: store-0.5.0 (dependency of funflow-1.3.1)
trying: lifted-async-0.10.0.2 (dependency of funflow-1.3.1)
next goal: async (dependency of funflow-1.3.1)
rejecting: async-2.2.1 (conflict: hinotify => async>=2.0 && <2.2)
rejecting: async-2.1.1.1, async-2.1.1, async-2.1.0, async-2.0.2 (conflict:
lifted-async => async>=2.2 && <2.3)
rejecting: async-2.0.1.6, async-2.0.1.5, async-2.0.1.4, async-2.0.1.3,
async-2.0.1.2, async-2.0.1.1, async-2.0.1.0, async-2.0.0.0 (conflict: store =>
async>=2.0.2)
rejecting: async-1.4, async-1.3, async-1.2, async-1.1, async-1.0 (conflict:
hinotify => async>=2.0 && <2.2)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: async, base, hinotify, funflow,
ff-client
```

Another user will be filing a ticket about how all versions are currently not buildable by stack (with any resolver) shortly. Currently the only way to successfully build funflow is from source via `cabal new-build` out of master.

**Comment by nc6** [comment]
Apologies for this. I updated funflow a couple of days ago to fix issues with more recent versions, but neglected to upload it to hackage. I'm doing that now. I'll also try building using cabal and check that that builds.

**Comment by nc6** [comment]
@KirinDave New version 1.3.2 is uploaded to hackage and builds successfully for me both with `stack build` and `cabal new-build`.

**Comment by KirinDave** [comment]
Works for me on a variety of machines. Thank you!
