### ISSUE TITLE
Requesting Custom User Effects Example

### ISSUE THREAD

**Issue by KirinDave** [tweag/funflow#98]
I'm currently writing a series of flows, and I've fallen into using the "stepIO a whole lot" pattern which you advice against. I'd like to convert to custom flows, but there aren't good examples of recommended patterns. Since Funflow is using a less well-discussed pattern around free arrows, it's not very easy to compare it to other projects to infer intended use.

Could we please have an example that helps establish:

1. The canonical way to call custom effects? (Are we supposed to use `effect` like in the tests, or `wrap'`?)
2. What's the right way to thread underlying state (e.g., connection pools) through interpreters.
3. For custom effects, are there preferred patterns for handling errors?

**Comment by nc6** [comment]
@KirinDave I've pushed an example that uses custom effects at https://github.com/tweag/funflow/commit/d168c91f4bf61f0167f6588be3d29c7237484c37. At the moment it doesn't cover using errors, but I can expand it to do so. I will also add additional documentation to try to explain what's going on, but let me know if this is useful and if not how I can improve it!
